controller:
  Tmax: 20
  step_time: 0.1
  weight_input: [1, 0.1]
  smooth_input: [1.0, 0.5]
  weight_slack: 1000
  clf_lambda: [1.0, 3.0]
  cbf_gamma: 1.0 # 3.0

robot:
  u_max: [2.0, 1.0]
  u_min: [-2.0, -1.0]
  vertexes: [[0, 0], [1.5, 0], [1.5, 0.8], [0.8, 0.8], [0.8, 1.5], [0, 1.5]]
  target_state: [12.0, 10.0, 0.0]
  destination_margin: 0.3
  sensor_range: 6.0
  margin: 0.1
  e0: 1e-6
  
# cir_obstacle_list:
#   obs_states: [
#     [5.5, 7.0]
#   ]
#   obs_radiuses: [0.7]
#   obs_vels: [
#     [0.6, 0.0]
#   ]
#   modes: [
#     'dynamic'
#   ]
  # obs_states: [
  #   [4.0, 4.0], [8.0, 8.0]
  # ]
  # obs_radiuses: [0.6, 0.6]
  # obs_vels: [
  #   [0.0, 0.0],
  #   [0.0, 0.0]
  # ]
  # modes: [
  #   'static', 'static'
  # ]

obstacle_list:
  obs_vertexes: [
    [[5.0, 3.0], [7.0, 3.0], [7.0, 4.0], [5.0, 4.0]],
    [[3.5, 7.0], [5.5, 7.0], [5.5, 8.0], [3.5, 8.0]]
  ]
  obs_vels: [
    [-0.6, 0.0],
    [0.55, 0.0]
  ]
  modes: [
    'dynamic', 'dynamic'
  ]
  # obs_vertexes: [
  #   [[9.0, 10.5], [12.0, 10.5], [12.0, 12.0], [9.0, 12.0]],
  #   [[9.0, 7.0], [12.0, 7.0], [12.0, 8.5], [9.0, 8.5]]
  # ]
  # obs_vels: [
  #   [0.0, 0.0],  
  #   [0.0, 0.0]
  # ]
  # modes: [
  #   'static', 'static'
  # ]