controller:
  Tmax: 20
  step_time: 0.1
  weight_input: [ 1.0, 1.0 ]
  smooth_input: [ 1.0, 0.5 ]
  weight_slack: 1000
  clf_lambda: [ 1.0, 3.0 ]
  cbf_gamma: 1.0 # 3.0

robot:
  model: 'unicycle'
  u_max: [ 2.0, 1.0 ]
  u_min: [ -2.0, -1.0 ]
  initial_state: [ 2.5, 2.0, 0.0 ]
  target_state: [ 12.0, 12.0, 0.0 ]
  destination_margin: 0.3
  width: 1.0  # half
  height: 0.5  # half
  sensor_range: 6.0
  margin: 0.1
  e0: 1e-3

cir_obstacle_list:
  obs_states: [
    [ 7.5, 7.5 ]
  ]
  obs_radiuses: [ 0.7 ]
  obs_vels: [
    [ 0.0, 0.0 ]
  ]
  modes: [
    'static'
  ]
  # obs_states: [
  #   [4.0, 4.0], [8.0, 8.0]
  # ]
  # obs_radiuses: [0.6, 0.6]
  # obs_vels: [
  #   [0.0, 0.0],
  #   [0.0, 0.0]
  # ]
  # modes: [
  #   'static', 'static'
  # ]

  # obstacle_list:
  #   obs_vertexes: [
  #     [[3.0, 4.0], [5.0, 4.0], [5.0, 5.0], [3.0, 5.0]],
  #     [[7.0, 7.0], [9.0, 7.0], [9.0, 8.0], [7.0, 8.0]]
  #   ]
  #   obs_vels: [
  #     [1.2, 0.0],
  #     [0.5, 0.2]
  #   ]
  #   modes: [
  #     'dynamic', 'dynamic'
  #   ]
  # obs_vertexes: [
  #   [[9.0, 10.5], [12.0, 10.5], [12.0, 12.0], [9.0, 12.0]],
  #   [[9.0, 7.0], [12.0, 7.0], [12.0, 8.5], [9.0, 8.5]]
  # ]
  # obs_vels: [
  #   [0.0, 0.0],  
  #   [0.0, 0.0]
  # ]
  # modes: [
  #   'static', 'static'
  # ]